[[patterns]]
name="auth"
hash=""
prefix_pattern= """
    var_d = global_a - 32;
    var_e = global_a - 32;
    if !((spender & 255) != Address(obj#0)) | ((from & 255) != Address(obj#0)) {
        amount;
        var_d = amount != 69;
        if var_d { var_e = amount == 11;
            if var_e {
                store_i64(spender + 16, from >>s 63);
                store_i64(spender + 8, from >>s 0);
            } else {
                store_i64(spender + 8, Error(Value, UnexpectedType));
                var_f = True;
            }
        } else {
            var_g = int.obj_to_i128_hi64(from);
            var_h = int.obj_to_i128_lo64(from);
            store_i64(spender + 16, var_g);
            store_i64(spender + 8, var_h);
        }
        if var_e || !var_d {
            var_f = False;
        }
        store_i64(spender, var_f);
        var_f = load_i64(var_d + 8);
        if var_f == 0 != 0 {
"""
suffix_pattern="""
            Void
        }
    }
    panic!("Unreachable code detected");
"""
body_replace = "spender.require_auth();"
